name: Release
on:
  push:
    branches:
      - dev
  release:
    types:
      - published
  workflow_dispatch:

# Cancel the previous beta runs (if any are still waiting)
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref == 'refs/heads/dev' }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm run test:jest

  build:
    runs-on: ubuntu-latest
    needs: test
    permissions:
      contents: read
      id-token: write
    environment:
      name: npm
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          registry-url: https://registry.npmjs.org/

      - name: Install npm dependencies
        run: npm ci

      - name: Run build
        run: npm run build

      - name: Update the package version
        if: github.ref == 'refs/heads/dev'
        run: node scripts/update-package-version.js $GITHUB_RUN_ID

      - name: Publish beta release
        if: github.ref == 'refs/heads/dev'
        run: npm publish --tag next --access public

      - name: Publish release
        if: github.ref != 'refs/heads/dev'
        run: npm publish --access public
